### ISSUE TITLE
Fix traefik - move to version 2.x

### ISSUE THREAD

**Issue by fais3000** [xamanu/xmpp-server#2]
@xamanu How do I setup xamanu/traefik. Docker-compose fails because docker is unable to download this image.

**Comment by xamanu** [comment]
Oh, you are right. I took this down, because it runs on an old version of traefik and I was in the process to migrate to the most recent. Let's use this issue to track this.

**Comment by xamanu** [comment]
Just gave it a first move in #3. This is untested still.

**Comment by xamanu** [comment]
@fais3000 after fixing a few things, that i wanted to do anyway, the current master should work. if you get certificate errors. wait a couple of minutes and restart, then they should be gone.

**Comment by xamanu** [comment]
@fais3000, the latest version here `version-0.8` is the state where I wanted to be and good for you to install. This is already running on my production site.

Will work on adding a turn server for the new audio/video call capabilities of Conversations and attaching ConverseJS to it.

Let me know how it works out.
Thank you!

**Comment by fais3000** [comment]
Actually I have been stuck with following issues.

1. When the versions are added e.g V0.7 next to the images, my
docker-compose fails by saying that image doesn't have labels defined. I
was able to pass though by removing versions.

2. Certificate errors don't go away in docker logs. I'm using cloudflare
for certificates and dns. An nginx reverse proxy then loads prosody. So may
be issue with the setup. However, I'm able to see prosody error messages so
the reverse proxy seems to be doing it's job and browser doesn't give a
certificate error.

3. Big issue for me. I've another chat app running on subdomain
chat.example.com and there seems to be this hardcoded in the docker setup
so I'm unable to change it to make it work. I see errors in log where some
script is looking for chat related paths even though my .env file have
messenger.example.com

4. My aim for setting all these up was to use converse js and file uploads.
For which http-bind is necessary. I'm still stuck with a 404 error on
xmpp.example.com/http-bind.

I can try again with your latest commit and let you know.

Thanks for the great work so far!

**Comment by xamanu** [comment]
> 1. When the versions are added e.g V0.7 next to the images, my
docker-compose fails by saying that image doesn't have labels defined. I
was able to pass though by removing versions.

It should work fine by running the `docker-compose.yml` with things like `image: xamanu/xmpp-prosody:version-0.8`. Double check. This will make things easier for you.

> 2. Certificate errors don't go away in docker logs. I'm using cloudflare
for certificates and dns. An nginx reverse proxy then loads prosody. So may
be issue with the setup. However, I'm able to see prosody error messages so
the reverse proxy seems to be doing it's job and browser doesn't give a
certificate error.

I kind of guess that you are running on an older container image and this has been fixed in the newest version. Try to get the version labels working, so your local docker setup is not caching extensively the `latest` container.

3. Big issue for me. I've another chat app running on subdomain
chat.example.com and there seems to be this hardcoded in the docker setup
so I'm unable to change it to make it work. I see errors in log where some
script is looking for chat related paths even though my .env file have
messenger.example.com

It is not hardcoded. You can use whatever domain you want.

> 4. My aim for setting all these up was to use converse js and file uploads.
For which http-bind is necessary. I'm still stuck with a 404 error on
xmpp.example.com/http-bind.

Yeah, conversejs is still on my to do list. Not working here.

**Comment by fais3000** [comment]
@xamanu I got some time to test this out again. I started from scratch on a new Digital Ocean droplet to avoid any confusions because of caching.

**Errors**
Certificate issue still persists. There are two set of errors. 

1. First from Prosody where it fails to find certificates from the config path for that specific Vhost. So it shows 3 errors for each domain.
2. Lets encrypt is unable to generate certs for the main xmpp domain. (I guess that is the root of above errors too) 
```level=error msg="Unable to obtain ACME certificate for domains \"xmpp```

Apart from that prosody and prosody filer seemed to be working. For my specific case traefik is causing unnecessary complexity because I've already got a reverse proxy (NGINX) working. However due to these certificate issues I have still failed to get prosody work with a client like conversejs yet.

May be having an alternative to Lets encrypt and having the ability to pass Certificates/keys paths for each domain in the env file may solve it for me.

**Comment by xamanu** [comment]
Hi @fais3000 , if you have already an reverse proxy, i guess this is what is causing the letsencrypt challenge to be successful and that might cause the cert errors. If you don't need traefik, then I would suggest to take the containers for the xmpp-server and xmpp-filer from Docker Hub and plug it into your system. If you provide valid certificates you can just mount them into the container and it should work.
